# Site settings
title: Abdullah Saei
name: Abdullah Saei

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/abdullahsaei
 - title: LinkedIn
   url: https://linkedin.com/in/abdullahsaei

#Any buzzword skills you want to include
skills:

 - Programming
 - Software Development
 - Hardware Development
 - Data Analysis
 - Networks
 - Wireless Communications
 - Embedded Systems
 - Linux
 - Android Development

#Work experience is required
roles:
 - title: Working Student: Technical Support
   start: 2018
   end: 2020
   employer: 2CP GmbH in Hamburg, Germany
   description: C/C++ Embedded Programming, Python and Qt5 GUI development, IT and Networks Support.
 - title: Research Assistant (HiWi)
   start: 2018
   end: 2018
   employer: ComNets Institute, Hamburg University of Technology (TUHH) in Hamburg, Germany
   description: C/C++ Embedded development for Wireless Networks, Matlab data analysis and data visualization, Research and Implementation of TSCH Protocol, Scripting to automate testbeds.
 - title: Professional Services Engineer
   start: 2017
   end: 2018
   employer: Universal Advanced Solutions in Cairo, Egypt
   description: Telecom technical support, Maintanince and Services for customers.

#Education is required
education:
 - level: Master of Science (M.Sc.)
   date: 2020
   subject: Information and Communication Systems
   school: Hamburg University of Technology (TUHH)
 - level: Bachelor of Science (B.Sc.)
   date: 2016
   subject: Electronics and Communications Engineering
   school: Misr International University (MIU)


intro: |
Throughout my years of studying Informatics engineering in Egypt and at TUHH, I have demonstrated a good level of academic achievement and have shown a particular strength in software and hardware development. I have been consistently engaged in projects, most of which involved designing and implementations - the experience that I believe would perfectly match with the position. For my research project in my master studies; it was at ComNets institute, I developed a power saving technique for 5G mobile network where I had to conduct a lot of simulations and data analysis in Object-Oriented Programming with Matlab. In addition to my academic background, I have experience working on various real-world projects where I have acquired practical skills in PCB designing, Hardwares, Sensors, Embedded Systems C/C++ programming and Scripting RPis. if not all, it also made a significant improvement in my non-cognitive skills such as time management, teamwork and communication with a diverse group of people.
